apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: cd
  name: cd
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: dockerreg.conygre.com:5000/cd/cd-server:1.0.0
    generation: null
    importPolicy:
       insecure: true
    name: 1.0.0
status:
  dockerImageRepository: ""
